version: "3.4"
services:
  neko:
    build:
      context: ../.docker/chromium-playwright
      dockerfile: Dockerfile
    restart: "unless-stopped"
    shm_size: "2gb"
    ports:
      - "8080:8080"
      - "52000-52100:52000-52100/udp"
      - "9222:9222"
      - "3000:3000"
    cap_add:
      - SYS_ADMIN
    environment:
      NEKO_SCREEN: '1920x1080@30'
      NEKO_PASSWORD: neko
      NEKO_PASSWORD_ADMIN: admin
      NEKO_EPR: 52000-52100
      NEKO_NAT1TO1: 192.168.219.102
      OPENAI_API_KEY: ${OPENAI_API_KEY}

